### PR TITLE
Created routes for signing up new user and logging in

### PR DESCRIPTION
**Pull request by AdamAlam**
Created backend route to create new user and login existing user.
Signs up a new user. (Hashes password on backend)
Dont forget to get the new .env from the discord

## Backend New User Request:
`POST` to `http://localhost:8000/signup`
Body:
```json
{
    "Email": "<NEW VALUE HERE>",
    "Username": "<UNIQUE USERNAME HERE>",
    "Password": "hellogoodsir",
    "DisplayName": "DN",
    "FirstName": "First",
    "LastName": "Last"
}
```
or
```sh
curl --location 'http://localhost:8000/signup' \
--header 'Content-Type: application/json' \
--data-raw '{
    "Email": "<NEW VALUE HERE>",
    "Username": "<NEW VALUE HERE>",
    "Password": "hellogoodsir",
    "DisplayName": "manamaadam",
    "FirstName": "AdamTest",
    "LastName": "LastTest"
}'
```
---

## Login User
`POST` to `http://localhost:8000/login`
params: email and password you just created.
Example:
```sh
curl --location --request POST 'localhost:8000/login?email=adam2%40test.com&password=hellogoodsir5'
```

### CODE REVIEW

**Comment by ShamsAsh** [comment]
Might need to update `requirements.txt`

**Comment by AdamAlam** [comment]
> Might need to update `requirements.txt`

@ShamsAsh I updated the requirements.txt

**Review by ShamsAsh — APPROVED** [review]

**Comment by WongDarren** [comment]
I get unauthorized trying to log in with your test password (probably expected, idk if that's the right password)
image
`http://localhost:8000/login?email=adam2%40test.com&password=hellogoodsir5`

But I'm getting 500 when i test with a new account i just made
image
`http://localhost:8000/login?email=wongdarren1997%40gmail.com&password=dummypass`


.env is updated to match new values in discord

**Comment by AdamAlam** [comment]
> I get unauthorized trying to log in with your test password (probably expected, idk if that's the right password) image `http://localhost:8000/login?email=adam2%40test.com&password=hellogoodsir5`
> 
> But I'm getting 500 when i test with a new account i just made image `http://localhost:8000/login?email=wongdarren1997%40gmail.com&password=dummypass`
> 
> .env is updated to match new values in discord

Make a new account with the sign up endpoint first, then use those login creds for the login endpoint.

You can also try logging in with:
email: `adam@test.com`
password: `hellogoodsir`

**Comment by WongDarren** [comment]
> > I get unauthorized trying to log in with your test password (probably expected, idk if that's the right password) image `http://localhost:8000/login?email=adam2%40test.com&password=hellogoodsir5`
> > But I'm getting 500 when i test with a new account i just made image `http://localhost:8000/login?email=wongdarren1997%40gmail.com&password=dummypass`
> > .env is updated to match new values in discord
> 
> Make a new account with the sign up endpoint first, then use those login creds for the login endpoint.
> 
> You can also try logging in with: email: `adam@test.com` password: `hellogoodsir`

Here's the dummy account i made
image

Unable to find both the one i just made and yours 
image

I know for sure its in the db
image

**Review by WongDarren — APPROVED** [review]

**Comment by WongDarren** [comment]
works for me

**Pull request merged**
